#pragma once

typedef enum IntroDataType {
	IntroDataType_bool,
	IntroDataType_char,
	IntroDataType_u8,
	IntroDataType_u16,
	IntroDataType_u32,
	IntroDataType_u64,
	IntroDataType_s8,
	IntroDataType_s16,
	IntroDataType_s32,
	IntroDataType_s64,
	IntroDataType_memIndex,
	IntroDataType_r32,
	IntroDataType_r64,
	IntroDataType_b32,
	IntroDataType_b64,
	IntroDataType_vec2,
	IntroDataType_quat,
	IntroDataType_dquat,
	IntroDataType_mat2,
	IntroDataType_mat3,
	IntroDataType_vec3,
	IntroDataType_mat4,
	IntroDataType_vec4,
	IntroDataType_something,
	IntroDataType_testEnumTwo,
	IntroDataType_Transform,
	IntroDataType_TestStruct,
	IntroDataType_game_Key,
	IntroDataType_game_Mouse,
	IntroDataType_fluffy_InputState,
	IntroDataType_game_Keyboard,
} IntroDataType;
